GET http://localhost:8080/people/4114
Accept: application/json

<> 2021-04-02T092918.200.json

###
POST http://localhost:8080/people
Content-Type: application/json

{
  "cpf": 12345,
  "name": "content"
}